/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function Island(props) {
    const { nodes, materials } = useGLTF("/scene.gltf");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={nodes.Sphere.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Box.geometry}
                material={nodes.Box.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polyhedron_4.geometry}
                material={nodes.Polyhedron_4.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polyhedron_3.geometry}
                material={nodes.Polyhedron_3.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polyhedron_2.geometry}
                material={nodes.Polyhedron_2.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polyhedron_1.geometry}
                material={nodes.Polyhedron_1.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Polyhedron.geometry}
                material={nodes.Polyhedron.material}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={nodes.Torus.material}
                position={[0, -1.05, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane.geometry}
                material={nodes.Plane.material}
                position={[0, 0.15, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane_1.geometry}
                material={nodes.Plane_1.material}
            />
        </group>
    );
}

useGLTF.preload("/scene.gltf");